---
title: "Discovery and inference of population structure in falciparum malaria"
author: "James Watson"
date: "05/11/2019"
output:
  html_document:
    df_print: paged
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T, cache.comments = FALSE, 
                      include = TRUE, 
                      fig.width = 12, fig.height = 12,
                      fig.pos = 'H', 
                      dev = 'png', dpi = 300)

library(fastcluster)
library(RColorBrewer)
library(dendextend)
library(ape)
```

## Load meta data and pairwise distance matrices

```{r}
# meta data on 1468 individuals 
load('RData/metadata.RData')

# 1468 x 1468 whole genome based pairwise 1-IBS distance matrix
load(file = 'RData/IBD_distance_matrix.RData')
IBD_WG = IBD_dist_matrix

# 1468 x 1468 whole genome pairwise 1-IBD distance matrix
load(file = 'RData/IBS_distance_matrix.RData')
IBS_WG = as.matrix(IBS_dist_matrix); rm(IBS_dist_matrix)

# 1468 x 1468 500,000 kb flanking region based pairwise 1-IBD distance matrix
load(file = 'RData/Chr_13_Flanking_radius_5e+05_IBD_dist_matrix.RData')
IBD_flanking = IBD_dist_matrix; rm(IBD_dist_matrix)

writeLines(sprintf('There are %s samples in total', nrow(metadata)))
```

Overview of the samples and of the mutations (Table 1 in the paper)
```{r}
table(metadata$Country)
table(metadata$k13Class, metadata$Country)
table(metadata$PLA1, metadata$Country)
table(metadata$crt_class, metadata$Country)
```

Make the -log_2 IBD distance matrix
```{r}
IBD_neglog2_WG = -log(1-IBD_WG, base = 2)
max_val = max(IBD_neglog2_WG[!is.infinite(IBD_neglog2_WG)])
IBD_neglog2_WG[IBD_neglog2_WG>max_val] = max_val
```


## Visualise whole genome pairwise distance matrices

This is Figure 1 in the paper

```{r IBS_versus_IBD}
par(las=1, mar = c(5,6,3,3), cex.axis=1.5, cex.lab=1.5, family = 'serif', bty='n')
layout(mat = matrix(c(1,2,3,4),nrow = 2,byrow = T))

h_IBS = hist(IBS_WG[upper.tri(IBS_WG)],breaks = 100,plot=F)
h_IBS$counts = log10(h_IBS$counts)
plot(h_IBS,main = '',ylab='Pairwise comparisons',xlab='1-IBS',yaxt='n', 
     col='lightgrey', border=NA)
axis(2, at = 1:5, labels = expression(10, 10^2, 10^3, 10^4, 10^5))
mtext(text='A', side = 3, adj = 0, line=0.5, cex=1.5)


h_IBD = hist(IBD_WG[upper.tri(IBD_WG)],breaks = 100,plot=F)
h_IBD$counts = log10(h_IBD$counts)
plot(h_IBD, xlab='1-IBD',ylab = 'Pairwise comparisons', 
     yaxt='n', col='lightgrey', border=NA,main='')
axis(2, at = 1:5, labels = expression(10, 10^2, 10^3, 10^4, 10^5))
mtext(text='B', side = 3, adj = 0, line=0.5, cex=1.5)

h_IBD_log = hist(IBD_neglog2_WG[upper.tri(IBD_neglog2_WG)],breaks = 100,plot=F)
h_IBD_log$counts[h_IBD_log$counts>0] = log10(h_IBD_log$counts[h_IBD_log$counts>0])
h_IBD_log$counts[h_IBD_log$counts==0] = NA
not_na_ind = complete.cases(h_IBD_log$counts)
plot(h_IBD_log, main='',ylab='Pairwise comparisons', xlab = '-log(IBD)',yaxt='n', 
     col='lightgrey', border=NA, ylim=range(h_IBD_log$counts,na.rm=T))
axis(2, at = 1:4, labels = expression(10, 10^2, 10^3, 10^4))
mtext(text='C', side = 3, adj = 0, line=0.5, cex=1.5)

plot(IBD_WG[lower.tri(IBD_WG)],  IBS_WG[lower.tri(IBS_WG)], pch='.',
     xlab = '1-IBD', ylab = '1-IBS')
mtext(text='D', side = 3, adj = 0, line=0.5, cex=1.5)
```

